// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ingshbnovyjuzeugmici.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZ3NoYm5vdnlqdXpldWdtaWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTc1MDAsImV4cCI6MjA2NzQ5MzUwMH0.TW3bw7cYilN470hEUMyZVVpbZD850g90NGai9n5ASK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});