// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dinjrfvnmwikjxtmzxsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbmpyZnZubXdpa2p4dG16eHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTUxNzQsImV4cCI6MjA2NzQ5MTE3NH0.Arr6BQaLvBnbYNLMbZcW0jEoB0MUjZIpSICYTi5swLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});